### PR TITLE
start running tests on CI

### LINKED ISSUE #30: add basic tests
so far, this repository has zero tests, which means it is very easy to break existing functionality during updates.

we need to add at least a few basic tests

### PR DESCRIPTION
**Pull request by ltalirz**
fixes #30

### CODE REVIEW

**Comment by peteboyd** [comment]
merged

**Comment by ltalirz** [comment]
@peteboyd Did you merge it, though?
Looks to me like you closed the PR, and the tests that it adds  are not in `master`.

I'm reopening this...

**Comment by ltalirz** [comment]
However, you did fix the issues that were pointed out by this PR, which is great.
I suggest you merge this, and afterwards I will make a new release

**Comment by ltalirz** [comment]
P.S. If you have a tiny bit of time could you add a few more CIFs to the `/tests/cif` folder that would make good test cases?
They will be picked up by the CI automatically, i.e. it will try to run `lammps-interface` on them

**Pull request merged**
